services:
  - type: worker  # Use 'worker' since this is a background task rather than a web service
    name: fastapi-websocket-client
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
